"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["gui.py"]
APP_NAME = "ProMan"

DATA_FILES = ['img/folder_small.png', 'img/settings_small.png', 'img/plus_small.png', 'img/sympathie_logo.ppm',
              'combobox.py', 'customer_project.py', 'copy_folders.py', 'configure.py', 'util.py']

OPTIONS = {'iconfile': 'img/butterfly.icns',
           'plist': {
               'CFBundleName': APP_NAME,
               'CFBundleDisplayName': APP_NAME,
               'NSHumanReadableCopyright': u"Copyright © 2016, Lovis Anderson, All Rights Reserved",
           },
           'argv_emulation': True,
           'packages': ['PIL']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
