"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
APP = ["gui.py"]
APP_NAME = "ProMan"
IMAGE_FILES = [os.path.abspath('img/folder_small.png'),
              os.path.abspath('img/settings_small.png'),
              os.path.abspath('img/plus_small.png'),
              os.path.abspath('img/sympathie_logo.ppm')]
DATA_FILES = ['combobox.py', 'customer_project.py', 'copy_folders.py', 'configure.py', 'util.py']

OPTIONS = {'iconfile': 'img/butterfly.icns',
           'plist': {
               'CFBundleName': APP_NAME,
               'CFBundleDisplayName': APP_NAME,
               'NSHumanReadableCopyright': u"Copyright © 2016, Lovis Anderson, All Rights Reserved",
           },
           'argv_emulation': True,
           'packages': ['PIL'],
           'resources': [('img', IMAGE_FILES), ]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
